// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DomDeMaioHomePage.Models.AutoGenerated.JsonResumeJsonTypes;

namespace DomDeMaioHomePage.Models.AutoGenerated.JsonResumeJsonTypes
{

    public class Award
    {

        [JsonProperty("description")]
        public string Description { get; set; }
    }

}
