// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DomDeMaioHomePage.Models.AutoGenerated.JsonResumeJsonTypes;

namespace DomDeMaioHomePage.Models.AutoGenerated.JsonResumeJsonTypes
{

    public class PhoneNumber
    {

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("number")]
        public string Number { get; set; }
    }

}
