using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Web.Script.Serialization;
using DomDeMaioHomePage.Models.AutoGenerated;
using DomDeMaioHomePage.Models;
using DomDeMaioHomePage.Translators;


namespace DomDeMaioHomePage.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Resume/

        public ActionResult Index()
        {
            var returnObject = GetResume();
            return View(returnObject);
        }

        public ActionResult Resume()
        {
            var returnObject = GetResume();
            return View(returnObject);
        }

        private Resume GetResume()
        {

            string strResumePath = System.Web.HttpContext.Current.Server.MapPath("~/App_Data/ddemaioResume.json");
            StreamReader sr = new StreamReader(strResumePath);
            string strResume = sr.ReadToEnd();
            sr.Close();
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            JsonResume resumeResponseObj = serializer.Deserialize<JsonResume>(strResume);


            Resume resume = ResumeTranslator.TranslateJsonToResume(resumeResponseObj);


            return resume;
        }

    }
}
