// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace DomDeMaioHomePage.Models.AutoGenerated
{

    public class JsonResume
    {

        [JsonProperty("firstName")]
        public string FirstName { get; set; }

        [JsonProperty("lastName")]
        public string LastName { get; set; }

        [JsonProperty("email")]
        public string Email { get; set; }

        [JsonProperty("address")]
        public Address Address { get; set; }

        [JsonProperty("phoneNumber")]
        public PhoneNumber[] PhoneNumber { get; set; }

        [JsonProperty("professionalExperience")]
        public ProfessionalExperience ProfessionalExperience { get; set; }

        [JsonProperty("education")]
        public Education Education { get; set; }
    }

}
