// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace DomDeMaioHomePage.Models.AutoGenerated
{

    public class ProfessionalExperience
    {

        [JsonProperty("jobs")]
        public Job[] Jobs { get; set; }

        [JsonProperty("proficiencies")]
        public Proficiency[] Proficiencies { get; set; }

        [JsonProperty("training")]
        public Training[] Training { get; set; }

        [JsonProperty("awards")]
        public Award[] Awards { get; set; }
    }

}
