// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace DomDeMaioHomePage.Models.AutoGenerated
{

    public class RotationalJob
    {

        [JsonProperty("jobTitle")]
        public string JobTitle { get; set; }

        [JsonProperty("division")]
        public string Division { get; set; }

        [JsonProperty("keyContributions")]
        public KeyContribution2[] KeyContributions { get; set; }
    }

}
